(defun move-line-up ()
  (interactive)
  (let ((current-line-start (line-beginning-position))
	(current-line-end (line-end-position)))
    (setq current-line-str (buffer-substring current-line-start current-line-end))
    (previous-line)
    (setq previous-line-str (buffer-substring (line-beginning-position) (line-end-position)))
    (delete-region (line-beginning-position) (line-end-position))
    (goto-char (line-beginning-position))
    (insert-string current-line-str)
    (next-line)
    (delete-region (line-beginning-position) (line-end-position))
    (goto-char (line-beginning-position))
    (insert-string previous-line-str))
)
